### ISSUE TITLE
Font inflation

### ISSUE THREAD

**Issue by ghost** [scriptituk/ttf2pscid2#2]
This may be just an artifact of Postscript fonts, but there is a doubling of size when converting a TTF to T42 font.
Is there any way to compress the size ? Is there a way to make it a binary file rather than a text file (to reduce the size) ?
I have ArialUnicodeMS which goes from a 23MB TTF to 46MB t42 file!

**Comment by scriptituk** [comment]
Greetings Michael - love the hat!

Use the -doptimise and -dcompress options to get a compressed binary Type42, e.g. 
`gs -q -o- -dNODISPLAY -doptimise -dcompress -sttf=arialuni.ttf ttf2pscid2.ps`
This converts ArialUnicodeMS from a 23MB TTF to a 15MB T42.
By default the T42 sfnts table is saved using postscript hex strings.

The README [Usage](https://github.com/scriptituk/ttf2pscid2#usage) section describes all the options.

Cheers, Raymond
