### ISSUE TITLE
Attempted to convert ttf file to cid file but ghostscript threw an error. It is asking for strintg.ps.

### ISSUE THREAD

**Issue by marmayogi** [scriptituk/ttf2pscid2#4]
$ gs -q -o- -dNOSAFER -dNODISPLAY -sttf=NotoSansTamil-VariableFont.ttf -st42=NotoSansTamil-VariableFont.cid  ttf2pscid2.ps
ERROR inc? need string.ps

Ghostscript's Version Details:
$ gs -v
GPL Ghostscript 9.55.0 (2021-09-27)
Copyright (C) 2021 Artifex Software, Inc.  All rights reserved.

**Comment by scriptituk** [comment]
The error was thrown by ttf2pscid2 not by ghostscript.
File string.ps is a dependency of ttf2pscid2.ps: it is in the scriptituk/pslutils repository.
Other dependencies from pslutils are: file.ps, sort.ps and math.ps.
If these are not present in the ttf2pscid2.ps directory then use -sinc=dir option to specify their location.
It is explained in the README.md document.
